// <auto-generated />
using System;
using Knowledge.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Knowledge.Server.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqliteKnowledgeDbContext))]
    partial class SqliteKnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Knowledge.Server.Knowledge.Domain.KnowledgeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkspaceId", "ParentId");

                    b.HasIndex("WorkspaceId", "Id", "CurrentRevisionId");

                    b.HasIndex("WorkspaceId", "Type", "Status");

                    b.ToTable("KnowledgeNodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_KnowledgeNodes_ParentIsNotSelf", "\"ParentId\" IS NULL OR \"ParentId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("Knowledge.Server.Knowledge.Domain.KnowledgeRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NodeId", "Version")
                        .IsUnique();

                    b.ToTable("KnowledgeRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_KnowledgeRevisions_VersionPositive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Knowledge.Server.Workspaces.Domain.Membership", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("Knowledge.Server.Workspaces.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Knowledge.Server.Workspaces.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("Knowledge.Server.Knowledge.Domain.KnowledgeNode", b =>
                {
                    b.HasOne("Knowledge.Server.Workspaces.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Knowledge.Server.Workspaces.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowledge.Server.Knowledge.Domain.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ParentId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowledge.Server.Knowledge.Domain.KnowledgeRevision", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "Id", "CurrentRevisionId")
                        .HasPrincipalKey("WorkspaceId", "NodeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentRevision");
                });

            modelBuilder.Entity("Knowledge.Server.Knowledge.Domain.KnowledgeRevision", b =>
                {
                    b.HasOne("Knowledge.Server.Workspaces.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Knowledge.Server.Knowledge.Domain.KnowledgeNode", null)
                        .WithMany("Revisions")
                        .HasForeignKey("WorkspaceId", "NodeId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowledge.Server.Workspaces.Domain.Membership", b =>
                {
                    b.HasOne("Knowledge.Server.Workspaces.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowledge.Server.Workspaces.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowledge.Server.Workspaces.Domain.Workspace", b =>
                {
                    b.HasOne("Knowledge.Server.Workspaces.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowledge.Server.Knowledge.Domain.KnowledgeNode", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
